### ISSUE TITLE
关于v1.2版本 install 时，“博客地址”输入框的异常

### ISSUE THREAD

**Issue by xiongdingbo007** [halo-dev/halo-admin#107]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

我在使用v1.2版本新建博客时，第二步填写博客信息的页面中。“博客地址”输入框无法正常的操作，现象是键盘的输入都不会更新这个输入框的值。而当更新“博客标题“输入框时，对“博客地址”输入框的最后一次键盘输入会体现效果。例如在“博客地址“输入框的末尾输入“123”，期初不会显示任何变化，但是填写“博客标题“后，“博客地址“末尾会增加“3”。

这个现象在我单独启动 halo-admin v1.2项目、编译并运行halo v1.2的发布版的源码（使用dev配置+mysql）、java -jar直接运行halo v1.2的发布版jar包时都有出现。 但是在我使用 halo-admin 主干的源码并单独启动时未出现问题，可以正常操作“博客标题“输入框。

鉴于主干中并未出现问题，请问这是已知问题吗，能否在v1.2发布版中把问题修复？（我查看了Installation.vue的近三月提交记录，但是并没有看出是什么修改解决了这个问题）

另外我觉得增加对于“博客地址“输入框的格式校验应该是个不错的主意。

**Comment by ruibaby** [comment]
这个我已经修了 https://github.com/halo-dev/halo-admin/commit/c50c78cd8e0a90b63e9dce3580fed17970e36bc6#diff-7bd31e812102872637f6b37bdc7f643aR229

你可以下载最新的 1.3.0-beta.3 在本地尝试一下，感谢反馈。https://github.com/halo-dev/halo/releases/tag/v1.3.0-beta.3

**Comment by xiongdingbo007** [comment]
> 这个我已经修了 [c50c78c#diff-7bd31e812102872637f6b37bdc7f643aR229](https://github.com/halo-dev/halo-admin/commit/c50c78cd8e0a90b63e9dce3580fed17970e36bc6#diff-7bd31e812102872637f6b37bdc7f643aR229)
> 
> 你可以下载最新的 1.3.0-beta.3 在本地尝试一下，感谢反馈。https://github.com/halo-dev/halo/releases/tag/v1.3.0-beta.3

感谢回复。我会着手切换到1.3版本为测试提供帮助。不过鉴于还没有更新的发布版，案例应该把1.2的发布版中的已知bug修复掉。

另外请问如果我想分别根据源码启动 halo 和 halo-admin 的话，除了删除halo现在自带的打包后的前段文件外，我还需要修改两个项目的哪些配置呢？

**Comment by ruibaby** [comment]
都不需要修改，两边都启动就好了。不过在登录页面你可能需要在右下角的设置里将 API 地址改为 halo 的启动地址。
