### ISSUE TITLE
升级1.3.0后，编辑自定义页面，发布时显示的文章链接后面出现undefined

### ISSUE THREAD

**Issue by LainNetWork** [halo-dev/halo-admin#114]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

如题，实际发布出去后，链接地址并没有受影响，应该是前端页面中的显示问题
![image](https://user-images.githubusercontent.com/20994069/77739599-bda8c080-704c-11ea-8c62-b07d49a06f4a.png)

**Comment by ruibaby** [comment]
你是不是只在后台点了 admin 更新？

**Comment by LainNetWork** [comment]
> 你是不是只在后台点了 admin 更新？

我升级了jar包的
> 版本：1.3.0
数据库：H2 1.4.196 (2017-06-10)
运行模式：production
User Agent：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by ruibaby** [comment]
尝试强制刷新一下页面。

**Comment by LainNetWork** [comment]
> 尝试强制刷新一下页面。

清除缓存，更换浏览器，刷新CDN后依旧存在此现象。只在自定义页面里有，其他地方的文章都是正常显示链接的

**Comment by ruibaby** [comment]
确实发现了这个问题，你可以尝试去博客设置右下角的高级设置里面，然后保存一下，看看能不能解决。

**Comment by LainNetWork** [comment]
> 确实发现了这个问题，你可以尝试去博客设置右下角的高级设置里面，然后保存一下，看看能不能解决。

似乎还是不行。话说自定义页面的路径设置，不知后续是否考虑允许设置前缀为空？也就是允许用户定义根路径，比如：https://lain.fun/${slug}，这样自由度更高一点

**Comment by ruibaby** [comment]
> > 确实发现了这个问题，你可以尝试去博客设置右下角的高级设置里面，然后保存一下，看看能不能解决。
> 
> 似乎还是不行。话说自定义页面的路径设置，不知后续是否考虑允许设置前缀为空？也就是允许用户定义根路径，比如：[https://lain.fun/${slug}，这样自由度更高一点](https://lain.fun/$%7Bslug%7D%EF%BC%8C%E8%BF%99%E6%A0%B7%E8%87%AA%E7%94%B1%E5%BA%A6%E6%9B%B4%E9%AB%98%E4%B8%80%E7%82%B9)

那样是很好，可是会造成很多路由冲突。必须写一连串的判断。

晚点我看看这个问题。
