### ISSUE TITLE
一人血书附件带文件夹功能

### ISSUE THREAD

**Issue by corgile** [halo-dev/halo-admin#131]
# 一人血书附件带文件夹功能
# 后台评论筛选下拉框自动选中 “待审核”
# 点击消息通知里面的评论后自动跳到待审核评论页面

**Comment by ruibaby** [comment]
血书呢？👀

**Comment by IceHL** [comment]
同求了，附带血书
![image](https://user-images.githubusercontent.com/42799766/94115414-424d8d80-fe7c-11ea-833c-57acab08f2c5.png)

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo/issues/1084
