### ISSUE TITLE
Halo 控制台创建的二级目录，在目标中不按照二级目录显示

### ISSUE THREAD

**Issue by Rambo1203** [halo-dev/halo-admin#178]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [Halo 使用文档](https://halo.run/guide)
- [ x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [ x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x] BUG 反馈
- [x ] 添加新的特性或者功能
- [x ] 请求技术支持

问题描述：
在 Halo / admin  控制台创建的 二级目录。在控制台可以看到二级目录的显示效果。但是在主题中都显示在一级中。

**Comment by ruibaby** [comment]
@Rambo1203 需要主题支持。

**Comment by Rambo1203** [comment]
直接修改主题的支持即可吗？我搞后端的，不知道主题的ZIP包的关键位置，是否可以知名一下，谢谢。我目前用的是 halo-theme-simple-bootstrap-1.3.0 这个主题

**Comment by ruibaby** [comment]
@Rambo1203 个人建议去作者的仓库提交 issue，如果想自己改的话可以参考  https://halo.run/archives/develop-theme-custom-tag#获取多级菜单列表
