### ISSUE TITLE
管理后台评论部分优化建议

### ISSUE THREAD

**Issue by hshanx** [halo-dev/halo-admin#217]
查看评论的时候，不知道评论是回复的谁

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈
- [x] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-admin/issues/119

**Comment by hshanx** [comment]
> #119

打扰了

**Comment by JohnNiang** [comment]
![image](https://user-images.githubusercontent.com/16865714/88147185-7499ff00-cc2f-11ea-8d4b-a0a2ec0560a1.png)
