### ISSUE TITLE
Login.vue verifyIsInstall 响应判断错误

### ISSUE THREAD

**Issue by 1205747671** [halo-dev/halo-admin#224]
- [x] BUG 反馈

```js
verifyIsInstall() {
      adminApi.isInstalled().then(response => {
        if (!response.data.data) {
          this.$router.push({ name: 'Install' })
        }
      })
    }
```
应该为
```js
verifyIsInstall() {
      adminApi.isInstalled().then(response => {
        if (!response.data) {
          this.$router.push({ name: 'Install' })
        }
      })
    }
```

**Comment by ruibaby** [comment]
你可以直接提交 pull request 。

**Comment by JohnNiang** [comment]
我认为这里没有问题。

response.data 的内容实际上是：

```json
{
    data: true
    devMessage: null
    message: "OK"
    status: 200
}
```

而我们需要判断其中的 data 是否为 true。

**Comment by 1205747671** [comment]
> 我认为这里没有问题。
> 
> response.data 的内容实际上是：
> 
> ```json
> {
>     data: true
>     devMessage: null
>     message: "OK"
>     status: 200
> }
> ```
> 
> 而我们需要判断其中的 data 是否为 true。

![image](https://user-images.githubusercontent.com/38599758/90306309-738e8180-defe-11ea-9fb6-bc4a92b26731.png)
可能是我这个服务有问题，我测试了最新版服务确实如你说的，`response.data.data` 是正确的。

**Comment by JohnNiang** [comment]
你是有自己修改过服务端代码么？似乎移出了统一 Wrapper。
