### ISSUE TITLE
Bug反馈：npm构建报错：Ｍodule not found: Error : Can't resolve 'core-js/modules/es6.array.copy-within

### ISSUE THREAD

**Issue by mebest100** [halo-dev/halo-admin#281]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [Ｘ ] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ X] BUG 反馈

Bug反馈：npm构建报错：Ｍodule not found: Error : Can't resolve 'core-js/modules/es6.array.copy-within：

![image](https://user-images.githubusercontent.com/11530991/104795904-ea50e300-57ec-11eb-8bea-7119a580f039.png)

解决办法： cnpm install core-js@2

**Comment by ruibaby** [comment]
应该只是因为你的网络问题导致依赖没有下载完整。这不是 bug。

**Comment by mebest100** [comment]
噢噢，可能把。

还有那个登录表单，我还是没有找到，这个是在你的CDN js/css文件里面吗，是哪个文件，能告知一下吗? 谢谢！

![image](https://user-images.githubusercontent.com/11530991/104796447-4158b700-57f1-11eb-8cdf-1a44f11df960.png)

**Comment by ruibaby** [comment]
https://github.com/halo-dev/halo-admin/blob/master/src/components/Login/LoginForm.vue

**Comment by mebest100** [comment]
但是还是有点不对：前端页面上登录两个字之间有一个空格（而且被span标签包裹），而LoginForm.vue的按钮文字上面的登录时没有空格的（也没有span标签）

![image](https://user-images.githubusercontent.com/11530991/104796696-94336e00-57f3-11eb-80a1-a45df92a388d.png)

![image](https://user-images.githubusercontent.com/11530991/104796753-115ee300-57f4-11eb-931e-f6dff94a138d.png)

![Uploading image.png…]()

**Comment by ruibaby** [comment]
@mebest100 去了解了解 Vue 和 ant design 吧，我们没有时间把所有东西给你讲清楚。

**Comment by mebest100** [comment]
OK, 还是非常感谢
