### ISSUE TITLE
博客设置里的“切换到高级/基础选项”按钮样式太违和了

### ISSUE THREAD

**Issue by Aienao** [halo-dev/halo-admin#321]
RT

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/115882305-39a74f00-a47f-11eb-93f2-c66800c9b016.png)

你那边是这样吗？

**Comment by Aienao** [comment]
![image](https://user-images.githubusercontent.com/49216568/115882652-8b4fd980-a47f-11eb-8eac-96a38c95759d.png)
edge 90.0.818.42

**Comment by ruibaby** [comment]
> ![image](https://user-images.githubusercontent.com/49216568/115882652-8b4fd980-a47f-11eb-8eac-96a38c95759d.png)
> edge 90.0.818.42

应该是浏览器兼容问题。

**Comment by ruibaby** [comment]
@Aienao 是 Edge 还是 Edge Chrome？

**Comment by Aienao** [comment]
> @Aienao 是 Edge 还是 Edge Chrome？

edge

**Comment by Aienao** [comment]
chrome正常

**Comment by Aienao** [comment]
> @Aienao 是 Edge 还是 Edge Chrome？

![image](https://user-images.githubusercontent.com/49216568/115883066-f4cfe800-a47f-11eb-88bf-63136b3bc8e0.png)

**Comment by ruibaby** [comment]
我没有办法在 Edge 复现。

**Comment by Aienao** [comment]
> 我没有办法在 Edge 复现。

上面贴的那个版本，是我打开【关于】界面后自动更新后的版本，此版本也复现不了了，更新前的版本有这问题。。。

**Comment by ruibaby** [comment]
> > 我没有办法在 Edge 复现。
> 
> 上面贴的那个版本，是我打开【关于】界面后自动更新后的版本，此版本也复现不了了，更新前的版本有这问题。。。

好吧，我会想办法解决一下。

**Comment by Aienao** [comment]
> > > 我没有办法在 Edge 复现。
> > 
> > 
> > 上面贴的那个版本，是我打开【关于】界面后自动更新后的版本，此版本也复现不了了，更新前的版本有这问题。。。
> 
> 好吧，我会想办法解决一下。
复现不了就算了，也不是啥大问题，close喽
