### ISSUE TITLE
关于编辑文章的工具栏建议

### ISSUE THREAD

**Issue by DuQingsong2002** [halo-dev/halo-admin#343]
![1](https://user-images.githubusercontent.com/59076088/123645617-128f4400-d859-11eb-8736-ad36be0b0e46.png)
![2](https://user-images.githubusercontent.com/59076088/123645634-14f19e00-d859-11eb-8c4a-6fcf8dc34cb6.png)

**Comment by DuQingsong2002** [comment]
不知道有没有快捷键，有的话建议鼠标放上工具栏选项能有对应的快捷键提示，我ctrl + 123确实可以设置标题，主要还是位置建议吧

**Comment by ruibaby** [comment]
key | keycode | 功能
-- | -- | --
F8 | 119 | 开启/关闭导航
F9 | 120 | 预览/编辑切换
F10 | 121 | 开启/关闭全屏
F11 | 122 | 开启/关闭阅读模式
F12 | 123 | 单栏/双栏切换
TAB | 9 | 缩进
CTRL + S | 17 + 83 | 触发保存
CTRL + D | 17 + 68 | 删除选中行
CTRL + Z | 17 + 90 | 上一步
CTRL + Y | 17 + 89 | 下一步
CTRL + BreakSpace | 17 + 8 | 清空编辑
CTRL + B | 17 + 66 | 加粗
CTRL + I | 17 + 73 | 斜体
CTRL + H | 17 + 72 | # 标题
CTRL + 1 | 17 + 97 or 49 | # 标题
CTRL + 2 | 17 + 98 or 50 | ## 标题
CTRL + 3 | 17 + 99 or 51 | ### 标题
CTRL + 4 | 17 + 100 or 52 | #### 标题
CTRL + 5 | 17 + 101 or 53 | ##### 标题
CTRL + 6 | 17 + 102 or 54 | ###### 标题
CTRL + U | 17 + 85 | ++下划线++
CTRL + M | 17 + 77 | ==标记==
CTRL + Q | 17 + 81 | > 引用
CTRL + O | 17 + 79 | 1. 有序列表
CTRL + L | 17 + 76 | 链接
CTRL + ALT + S | 17 + 18 + 83 | ^上角标^
CTRL + ALT + U | 17 + 18 + 85 | - 无序列表
CTRL + ALT + C | 17 + 18 + 67 | ``` 代码块
CTRL + ALT + L | 17 + 18 + 76 |  
CTRL + ALT + T | 17 + 18 + 84 | 表格
CTRL + SHIFT + S | 17 + 16 + 83 | 下角标
CTRL + SHIFT + D | 17 + 16 + 68 | 中划线
CTRL + SHIFT + C | 17 + 16 + 67 | 居中
CTRL + SHIFT + L | 17 + 16 + 76 | 居左
CTRL + SHIFT + R | 17 + 16 + 82 | 居右
SHIFT + TAB | 16 + 9 | 取消缩进

你说的固定工具栏应该有人提过了，我们会在 1.5.x 进行优化。
