### ISSUE TITLE
菜单排序编号不能录入

### ISSUE THREAD

**Issue by Nonoas** [halo-dev/halo-admin#384]
### What is version of Halo has the issue?

1.4.13

### What database are you using?

MySQL 8.x

### What happened?

数据库有priority字段，但是前端没有录入的输入框

**Comment by ruibaby** [comment]
你可以使用这个图标拖动，然后点击保存即可。

![image](https://user-images.githubusercontent.com/21301288/143771415-17d5daaf-7062-4abe-9870-a32ee9881ad9.png)
