### ISSUE TITLE
单独部署，screenshot.png不走api地址

### ISSUE THREAD

**Issue by Nonoas** [halo-dev/halo-admin#386]
### 是什么版本出现了此问题？

1.4.13

### 使用的什么数据库？

MySQL 8.x

### 在线站点地址

http://admin.nonoas.top/

### 发生了什么？

![image](https://user-images.githubusercontent.com/54799528/143859351-0581fe5d-4d71-4918-850d-6bbb06b957a2.png)

之前应该有个按钮的吧

**Comment by ruibaby** [comment]
看 README，建议不要使用 master 分支的代码直接部署。

**Comment by ruibaby** [comment]
> 为啥screenshot.png走的不是api路径（8091）呢

@Nonoas 这是目前已知的缺陷。

**Comment by Nonoas** [comment]
> @Nonoas 这是目前已知的缺陷。

目前有修复吗？这个有什么修改方案吗？我可以怎么改？我对前端的代码不太了解
