### ISSUE TITLE
优化分类目录中对于加密分类的展示方式

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo-admin#394]
### 描述一下此特性

如下图所示，分类树结构为：
```
——测试分类1（加密）
————测试分类1-1
————测试分类1-2
```
当测试分类1为加密状态时其子分类应该也展示为加密状态会更好
![image](https://user-images.githubusercontent.com/38999863/145158473-c14f332f-84ce-4bf3-8e2e-69553ad79c12.png)

**Comment by leaderzhang** [comment]
我能顺带提一个加密需求嘛，其实很简单，加密文章也能在前台进行展示出来。加密分类这个其实有些臃肿，我们为什么不直接可以把加密文章在前台展示。类似hexo的那种加密就好了啊
