### ISSUE TITLE
管理后台支持从本地加载静态资源库

### ISSUE THREAD

**Issue by parasomn1a** [halo-dev/halo-admin#398]
### 你当前使用的版本

1.4.16

### 描述一下此特性

需要一个开关用于从本地加载静态资源（css、js等）以应对 jsdelivr 国内访问速度不佳的情况。

**Comment by ruibaby** [comment]
目前已经取消使用 jsDelivr CDN，目前做切换 CDN 的开关比较复杂，但我们后续会研究一下。
