### ISSUE TITLE
Request to switch to the new layers mode instead of conservative purge mode

### ISSUE THREAD

**Issue by JohnNiang** [halo-dev/halo-admin#415]
### Your current Halo version

latest

### Describe this feature

Request to switch to the new layers mode instead of conservative purge mode. The `conservative` purge mode will be removed in Tailwind 2.0.

### Additional information

```bash
+ pnpm build

> halo-admin@1.4.15 build /home/jenkins/agent/workspace/my-devops-projectdq8jj/halo-admin-pipeline
> vue-cli-service build


-  Building for production...

warn - The `conservative` purge mode will be removed in Tailwind 2.0.
warn - Please switch to the new `layers` mode instead.
```

**Comment by ruibaby** [comment]
I will try to upgrade Tailwind CSS to the latest version

**Comment by ruibaby** [comment]
![image](https://user-images.githubusercontent.com/21301288/150280010-bf04fe3b-3c55-4d8b-a961-adf583b92fd2.png)
