### ISSUE TITLE
功能请求：标签选择时可以按一定顺序排列

### ISSUE THREAD

**Issue by owlrock7** [halo-dev/halo-admin#428]
### Your current Halo version

halo-1.4.17

### Describe this feature

在发布文章时，默认标签选择是按照创建时间排序。因为创建的标签比较多，需要逐个查看后选择标签，能否增加按a-z顺序排列标签，这样要选的标签就能下拉快速选择。

**Comment by ruibaby** [comment]
@owlrock7 有没有兴趣参与呢，这个应该只需要在前端修改接口参数，或者在前端做排序即可。

**Comment by owlrock7** [comment]
以我有限的只能看懂 html css 的水平，可能距离修改 vue 还差不少，这次只能靠您有空改一下了，非常感谢。
另祝虎年身体康泰，虎虎生威！
