### ISSUE TITLE
需要对现有代码作出一些改动以支持文章版本管理

### ISSUE THREAD

**Issue by guqing** [halo-dev/halo-admin#438]
### 描述

改动如下：
1. 将预览前保存文章的接口调用改为`/{postId}/status/draft/content`即调用SDK为`apiClient.post.updateDraftById(this.postToStage.id, this.postToStage.originalContent)`
2. SDK的`BasePostSimple`对象增加`isInProces`属性
3. 增加对`inProgress`的展示，表示是否有正在编辑中的草稿
4. 前端文章预览方法中去掉`this.postToStage.status = 'DRAFT'`
5. 保存草稿按钮去掉

以上描述中有关Post的也要相应改动Sheet

Related issue: [halo#1587](https://github.com/halo-dev/halo/issues/1587)
Related PR: [halo#1617](https://github.com/halo-dev/halo/pull/1617)

**Comment by JohnNiang** [comment]
建议：isInProcess -> wip(work in progress)

**Comment by guqing** [comment]
> 建议：isInProcess -> wip (work in progress)

之前想用来着但是wip是缩写应该大写WIP 而且表示boolean 所以就放弃了这个想法，isInProcess更恰当些感觉

**Comment by guqing** [comment]
> 这里推荐用 `in-progress`，而不是 `is-in-process`。`in-progress` 更正式一些，像 GitLab 等都在使用 WIP（Work In Progress）。
> 
> 参考：
> 
> * https://writingexplained.org/work-in-progress-or-work-in-process
> * https://about.gitlab.com/blog/2016/01/08/feature-highlight-wip/
> * https://gitlab.com/gitlab-org/gitlab/-/blob/master/db/structure.sql?expanded=true&viewer=simple#L13959

好的
