### ISSUE TITLE
文章发布时间BUG

### ISSUE THREAD

**Issue by mrdong916** [halo-dev/halo-admin#45]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**涉及功能**：写文章-> 发布 -> 发布时间
**BUG 描述** ：
仅变更月或者年，发布时间无法改变，只有变更时点击日才可以改变发布时间， 复现率100%

尝试做过修复，发现项目用的ant-design-vue 有点鸡肋，不过根据官方给出的公共事件`panelChange`，可以获取的内容如图，不清楚是ant-design-vue的BUG还是此项目的BUG

![WX20190917-224905@2x.png](https://i.loli.net/2019/09/17/z1pjvy4ZLCMrOAf.png)

尝试修复时测试的代码

html
```
<a-date-picker
                  showTime
                  :defaultValue="pickerDefaultValue"
                  format="YYYY-MM-DD HH:mm:ss"
                  placeholder="选择文章发表时间"
                  @change="onPostDateChange"
                  @ok="onPostDateOk"
                  @panelChange="onChangeTest"
                />
```
method:
```
onPostDateChange(value, dateString) {
      console.log('更改日期回调 => ' + value)
      this.selectedPost.createTime = value.valueOf()
    },
    onPostDateOk(value) {
      console.log('点击确定按钮回调 => ' + value)
      this.selectedPost.createTime = value.valueOf()
    },
    onChangeTest(value, mode) {
      console.log('日期 时间公共变更回调 => ' + value)
      console.log('当前变更组件类型 => ' + mode)
      this.selectedPost.createTime = value.valueOf()
      this.time = value.valueOf()
    }
```

另外：发布文章时选择分类目录，点击分类名称，无法自动选中，同样发现此项目直接用的ant-design-vue的，ant-design-vue并没有给出此功能，建议进行优化此功能。

**Comment by ruibaby** [comment]
@mrdong916 好的，非常感谢你的反馈，我们会尝试修复这些问题。另外，如果你有时间也可以帮忙修复哦。

**Comment by JohnNiang** [comment]
好的，后面我们尝试解决此问题。

感谢反馈！

**Comment by guqing** [comment]
你好 我测试了一下 不论是发布还是编辑 单独修改年/月/时间  都没有测试出来这个问题 请问你下你使用的是哪个版本呢？

**Comment by mrdong916** [comment]
@guqing 最新版本，如无法复现可以联系我QQ31639971
