### ISSUE TITLE
1.5.0-alpha.1版 关于附件的问题

### ISSUE THREAD

**Issue by zihanla** [halo-dev/halo-admin#488]
### 是什么版本出现了此问题？

1.5.0-alpha.1

### 使用的什么数据库？

H2

### 使用的哪种方式部署？

Docker

### 在线站点地址

https://hxcpl.cn

### 发生了什么？

比如 我上传了一个名叫 子涵.jpg的图片
然后绝的有点小问题就去删除了，修改
然后重新上传，图片的样式还是没修改前的样式(清理过缓存) 
然后我把图片名改成子涵1.jpg
清缓存刷新 图片才改变样式

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo-admin/pull/491 中尝试过处理这个问题，但是效果并不理想。考虑到这算是一个低频的操作，建议有这种情况的时候手动开启浏览器开发者控制台的 Disable cache 再刷新一次即可解决。我们在下一个 major 版本会考虑如何规避这个问题。
