### ISSUE TITLE
`亮色菜单风格` 选项使用了错误的暗色风格图片

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [halo-dev/halo-admin#522]
### 是什么版本出现了此问题？

v1.5.0

### 发生了什么？

在 `后台布局设置` 的 `整体风格设置` 中，`亮色菜单风格` 选项使用了错误的暗色风格图片。

### 附加信息

![image](https://user-images.githubusercontent.com/27671436/160104186-e423acac-148e-4900-b508-022922f6bb67.png)

**Comment by QuentinHsu** [comment]
> /kind bug
> /assign @QuentinHsu 

收到
