### ISSUE TITLE
文章编辑器输入法遮挡文字

### ISSUE THREAD

**Issue by cetr** [halo-dev/halo-admin#528]
### 是什么版本出现了此问题？

1.5

### 使用的什么数据库？

MySQL 8.x

### 发生了什么？

环境：win10、Google Chrome、微软输入法，其他没试

![image](https://user-images.githubusercontent.com/49756728/160665884-e38945c4-87c0-447b-bc9f-3aac20f52d29.png)

**Comment by JohnNiang** [comment]
我也遇到了同样的问题。

![image](https://user-images.githubusercontent.com/16865714/160727326-61f0ec95-2e6a-4acf-9859-35f1d196869b.png)

不过在 https://codemirror.net/ 上编辑中文是没有问题的。

![image](https://user-images.githubusercontent.com/16865714/160727660-e61fc947-fee7-435b-b169-17d1ae05d2b1.png)


/kind bug
