### ISSUE TITLE
评论列表『通过并回复』按钮点击无反应

### ISSUE THREAD

**Issue by bihell** [halo-dev/halo-admin#86]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [Halo 使用文档](https://halo.run/guide)
- [x] [Github Wiki 常见问题](https://github.com/halo-dev/halo/wiki/4.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [x] [其他 Issues](https://github.com/halo-dev/halo-admin/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈
- [ ] 添加新的特性或者功能
- [ ] 请求技术支持

**Comment by ruibaby** [comment]
可以复现吗？F12看看错误信息。

**Comment by bihell** [comment]
> 可以复现吗？F12看看错误信息。

可以复现，你项目新起，默认的文章不是有一条需要审核的评论么，你点了以后没报错，也没任何请求发出

如果你在群里的话可以@一下我， qq: 48384453 ，我录一段视频给你

**Comment by ruibaby** [comment]
@bihell 我这里没有复现成功，请问你是什么版本。

**Comment by bihell** [comment]
Master分之最新的

**Comment by bihell** [comment]
@ruibaby 最新的master分支

**Comment by ruibaby** [comment]
> @ruibaby 最新的master分支

刚刚发布 beta.2 重新测了下，也没出现问题。

**Comment by bihell** [comment]
@ruibaby 那可能是我自己系统环境关系吧，那就别管了
